config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root "tweets#index"

  get "tweets/world"
  get "tweets/search"
  resources :tweets do
    resources :comments, only: [:create, :destroy]
  end


  get "messages/index"
  get "groups/index"
  resources :groups do
    resources :messages
  end

  resources :relationships,only: [:create, :destroy]
  resources :users,only: [:index, :edit, :update, :show] do
    member do
      get :following, :followers
    end
    
    resources :tweets do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end  
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  
  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      if last_message.content?
        last_message.content
      else
        '画像が投稿されています'
      end
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_chat_header.html.haml
.chat-header
  .chat-header__serch

  .chat-header__post.grid-1
    -# = link_to new_tweet_path, class: "post" do
    -#   = icon('fas', 'pen-square', class: 'icon')
    -#   %span 投稿

  .chat-header__sign
    -if user_signed_in?
      .user_nav.grid-2
        = link_to "グループ作成", new_group_path
        = link_to "マイページ", "/users/#{current_user.id}",class:"grid-1"
        = link_to "ログアウト", destroy_user_session_path, method: :delete,class:"grid-1"
        -# = icon('fas', 'cog', class: 'icon')
      
    -else
      .grid-2
        = link_to "ログイン", new_user_session_path, class: 'post'
        = link_to "新規登録", new_user_registration_path, class: 'post' 
  
  

app/views/messages/_main_chat.html.haml
= render "tweets/modules/side_bar"
= render 'messages/chat_header'

.chat-title
  .chat-title__explanation
    %h1
      グループ:
      = @group.name
  .header-a
    .header-a__group
      %h2.header__group__name
        
      %p.header__group__member 
        メンバー :
        - @group.users.each do |user|
          = image_tag user.icon_image.url,class:"member-image"
          -# = user.nickname
    %p.header__group-edit
      = link_to 'グループ編集', edit_group_path(@group) 
  

.chat-main
  


  .message
    = render 'layouts/modules/notifications'
    = render @messages
  


  .forms
    = form_with model: [@group, @message] do |f|
      .form
        = f.text_field :content, class: 'form__text',    placeholder: 'メッセージの入力をしてください'
        .input
          = f.label :image, class: 'input__file' do
            = icon('fas', 'camera-retro', class: 'image')
            = f.file_field :image, class: 'file'
      = f.submit '送信', class: 'send-btn'

app/views/messages/_message.html.haml
.messages
  .messages__left
    %ul.messages__left__name 
      = image_tag message.user.icon_image.url,class:"chat-image"
      = message.user.nickname
    .messages__left__date
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
  .messages__comment
    - if message.content.present?
      %p.lower-message__content
        = message.content
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/_side_bar.html.haml
.sub-chat-bar
  .connect-groups
    グループリスト
    - current_user.groups.each do |group|
      .connect-groups__lists
        .connect-groups__lists__name
          %h3
            = link_to group_messages_path(group) do
              %p.group-name
                = group.name
              %p.group-edit 
                = link_to edit_group_path(group) do
                  = icon('fas', 'object-group', class: 'icon')
        .connect-groups__lists__member   
          %p.header__group__member 
            - group.users.each do |user|
              = group.show_last_message
              -# = user.nickname




  

app/views/messages/edit.html.haml
= form_with model:@group do |f|
  = f.text_field :name, class: "chat-group-form__input", placeholder: "グループ名を入力してください"
  = f.collection_check_boxes :user_ids, User.all, :id, :name
  = f.submit "Save", class: "chat-group-form__action-btn"

app/views/messages/index.html.haml
.wrapper
  -# = render "tweets/modules/sidebar"
  = render "messages/main_chat"
  = render "messages/side_bar"

app/views/messages/new.html.haml
=form_with model:@group do |f|
  = f.text_field :name, class: "chat-group-form__input", placeholder: "グループ名を入力してください"
  = f.collection_check_boxes :user_ids, User.all, :id, :name
  = f.submit "Save", class: "chat-group-form__action-btn"