config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root "tweets#index"

  get "tweets/world"
  get "tweets/search"
  resources :tweets do
    resources :comments, only: [:create, :destroy]
  end


  get "messages/index"
  get "groups/index"
  resources :groups do
    resources :messages
  end

  resources :relationships,only: [:create, :destroy]
  resources :users,only: [:index, :edit, :update, :show] do
    member do
      get :following, :followers
    end
    
    resources :tweets do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet, counter_cache: :likes_count
  belongs_to :user

  validates :user_id, presence: true
  validates :tweet_id, presence: true
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_tweet, only: [:create, :destroy]

  def create
    @like = Like.create(user_id: current_user.id, tweet_id: params[:tweet_id])
    @likes = Like.where(tweet_id: params[:tweet_id])
    redirect_to root_path
    
    # unless like.save
    #   flash.now[:alert] = like.errors.full_messages
    # end
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, tweet_id: params[:tweet_id])
    @like.destroy
    @likes = Like.where(tweet_id: params[:tweet_id])
    redirect_to root_path

    # unless like.destroy
    #   flash.now[:alert] = '削除できませんでした。'
    # end
  end

  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.haml
-# #ユーザーがサインインしているかどうか
- if user_signed_in?
  -# #ログインしているユーザーがすでに「いいね」しているかどうか
  - if tweet.like_user(current_user.id)
    .tweet-button-container__left__dislike
      =link_to user_tweet_like_path(current_user, tweet), method: "DELETE", remote: true do
        %i.fas.fa-heart
        %span いいね！
        %span 
          = tweet.likes_count
  - else
    .tweet-button-container__left__like
      =link_to user_tweet_likes_path(current_user, tweet), method: "POST", remote: true do
        %i.fas.fa-heart
        %span いいね！
        %span
          = tweet.likes_count
-else
  .tweet-button-container__left__like
    %i.fas.fa-heart
      %span いいね！
      %span 
        = tweet.like_count

app/views/likes/create.js.haml
$(".tweet-button-container__left").html("#{escape_javascript(render partial: 'like', locals: { tweet: @tweet, tweets: @tweets, likes: @likes, like: @like})}");

app/views/likes/destroy.js.haml
$(".tweet-button-container__left").html("#{escape_javascript(render partial: 'like', locals: { tweet: @tweet, tweets: @tweets, likes: @likes, like: @like})}");