config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root "tweets#index"

  get "tweets/world"
  get "tweets/search"
  resources :tweets do
    resources :comments, only: [:create, :destroy]
  end


  get "messages/index"
  get "groups/index"
  resources :groups do
    resources :messages
  end

  resources :relationships,only: [:create, :destroy]
  resources :users,only: [:index, :edit, :update, :show] do
    member do
      get :following, :followers
    end
    
    resources :tweets do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :comments
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
  has_many :likes, dependent: :destroy

  has_many :active_relationships, class_name:  "Relationship",foreign_key: "follower_id",dependent: :destroy
  has_many :passive_relationships, class_name:  "Relationship",foreign_key: "followed_id",dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  validates :nickname, presence: true, uniqueness: true
  mount_uploader :icon_image, UserIconUploader

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,only: [:edit, :show]
  before_action :follow_user,only: [:following, :followers]

  def index
  end
  
  def edit
  end

  def update
      if current_user.update(user_params)
        redirect_to user_path(current_user.id)
      else
        redirect_to edit_user_path(current_user.id)
    end
  end

  def show
    @user = User.find(params[:id])
    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweets.page(params[:page]).per(10).order("created_at DESC")
    @icon_image = user.icon_image
    @profile = user.profile
    @email = user.email
  end


  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end


  private

  def user_params
    params.require(:user).permit(:nickname, :email, :name ,:icon_image, :profile)
  end

  def set_user
    @users = User.all.page(params[:page]).per(3).order("created_at DESC")
  end

  def follow_user
    @follow_users = User.all.page(params[:page]).per(3).order("created_at DESC")
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
 end

  # def gravatar_for(user)
  #   gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
  #   gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
  #   image_tag(gravatar_url, alt: user.name, class: "gravatar")
  # end
end

app/views/users/_follow.html.haml
= form_for(current_user.active_relationships.build) do |f|
  = hidden_field_tag :followed_id, @user.id
  = f.submit "Follow", class: "btn btn-primary"

app/views/users/_follow_form.html.haml
-unless current_user?(@user)
  #follow_form
  -if current_user.following?(@user)
    = render 'unfollow'
  -else
    = render 'follow'

app/views/users/_stats.html.haml
.follow
  -@user ||= current_user
  .stats
    =link_to following_user_path(@user),class:"follow-btn" do
      %p フォロー 
      .strong#following.stat
        =@user.following.count
       
    
    =link_to followers_user_path(@user),class:"follow-btn" do
      %p フォロワー
      .strong#followers.stat
        = @user.followers.count

    =link_to user_path(@user),class:"follow-btn" do
      %p ツイート数
      .strong#followers.stat
        = @user.tweets.count
       
      

app/views/users/_unfollow.html.haml
= form_for(current_user.active_relationships.find_by(followed_id: @user.id),html: { method: :delete }) do |f|
  = f.submit "Unfollow", class: "btn"

app/views/users/edit.html.haml
=render "users/modules/sidebar"
=render "users/modules/header"
=render "users/modules/show_sub_bar"


.user-edit

  #account-page.account-page
    .account-page__inner.clearfix
      .account-page__inner--left.account-page__header
        %h5 アカウントの編集
  
      .account-page__inner--right.user-form
        = form_with model:(current_user) do |f|
          .field
            .field-label
              = f.label :nickname
              %span 必須
            .field-input
              = f.text_field :nickname, autofocus: true
          .field
            .field-label
              = f.label :email
              %span 必須
            .field-input
              = f.email_field :email, autofocus: true

          .field
            .field-label
              = f.label :name
            .field-input
              = f.text_field :name
          .field
            .field-label
              = f.label :profile
            .field-input
              = f.text_area :profile
          .field
            .field-label
              = f.label :icon_image
            .field-input
              = f.file_field :icon_image

          .actions
            = f.submit "Update", class: 'btn'

app/views/users/following.html.haml
-# -@user.followings.each do |user|
-#   %table
-#   %tr
-#     %td 
-#       = user.nickname
-#     %td
-#       = link_to '詳細', user_path(user)

app/views/users/profile.html.haml
=render "users/modules/sidebar"
=render "users/modules/header"
=render "users/modules/sub_bar"

.profile
  .profile__top


.profile-lists
  .profile-lists__top
    .profile-image
      =image_tag("gest.fujita.jpeg",class:"top-logo")
      -# =img_tag
      -# =current_user.image
    .profile-text
      .profile-text__name
        =current_user.name
      .profile-text__nickname
        =current_user.nickname
      .profile-text__email
        =current_user.email

  .profile-lists__profile

app/views/users/search.html.haml
=render "users/modules/sidebar"
=render "users/modules/header"
=render "users/modules/show_sub_bar"

app/views/users/show.html.haml
=render "users/modules/sidebar"
=render "users/modules/header"
=render "users/modules/show_sub_bar"




.profile-lists
  .profile-lists__top
 
    .profile-image
      -if @icon_image.url.nil?
      -else
        = image_tag @icon_image.url

    .profile-text
      .profile-text__nickname
        %i.far.fa-laugh-squint
        =@nickname
      .profile-text__email
        %i.far.fa-envelope
        = @email
      .profile-text__profile
        %i.far.fa-id-card
        = simple_format @profile


 
  .follow
    =render "stats"
    =render "follow_form"






  .my-tweet
    = @nickname 
    さんの投稿一覧   
    .my-tweet__lists
      -@tweets.each do |tweet|

        .tweet-lists__list
          .user-tweet
            .user-tweet__image
              -if current_user.icon_image.url.nil?
              -else
                =link_to image_tag tweet.user.icon_image.url
            .user-tweet__nickname
              -# = tweet
          .user-text
            =link_to tweet_path(tweet.id) do
              .user-text__first
                .date-time
                  = tweet.created_at.strftime('%Y/%m/%d')
                .tweet-link
                  = link_to '詳細', "/tweets/#{tweet.id}", method: :get 
                  -if user_signed_in? && current_user.id == tweet.user_id
                    = link_to '編集', "/tweets/#{tweet.id}/edit", method: :get
                    = link_to '削除', "/tweets/#{tweet.id}", method: :delete 
        
              .user-text__second
                .user_name
                  = simple_format(tweet.text)

              .user-text__third
                -# .kuchikomi
                -#   ■
                %i.fas.fa-heart
                  = tweet.likes_count
      = paginate(@tweets)

app/views/users/show_follow.html.haml
=render "users/modules/sidebar"
=render "users/modules/header"
=render "users/modules/follow_sub_bar"


.profile-lists
  .profile-lists__top
 
    .profile-image
      -if @user.icon_image.present?
        = image_tag @user.icon_image.url
        

    .profile-text
      .profile-text__nickname
        %i.far.fa-laugh-squint
        =@user.nickname
      .profile-text__email
        %i.far.fa-envelope
        = @user.email
      .profile-text__profile
        %i.far.fa-id-card
        = simple_format @user.profile


  .follow
    =render "stats"
    =render "follow_form"



-# ---フォローリスト---
.user-follow_lists
  -provide(:title, @title)
  .row
    .col-md-4
    -if @users.any?
      .user_avatars
        -@users.each do |user|
          %section.user_info
            -# -if @user.icon_image.present?
            -#   -# = image_tag @user.icon_image.url
            -# -else
      
            -# %h1
            -#   = @user.name
            -# %span
            -#   = link_to "マイページ", @user 
            -# %span
            -#   %b ツイート数:
            -#   = @user.tweets.count

          %section.stats
            =link_to user_path(user.id) do
              -# = render 'users/stats' 
              .follow_list
                .follow-image
                  -if user.icon_image.present?
                    = image_tag user.icon_image.url
                  -else
                
                .follow-text
                  %p
                    = user.nickname
                  %p
                    = user.profile
            
           

                    
              
      
    -# .col-md-8
    -#   %h3
    -#     = @title
    -#   -if @users.any? 
    -#     %ul.users.follow
          -# = render @users
      
    -#     = will_paginate
 

app/views/users/user_list.html.haml
.user-list
  -users.each do |user|
    -if user.name.nil?
      0
    -else
      =user.name