config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root "tweets#index"

  get "tweets/world"
  get "tweets/search"
  resources :tweets do
    resources :comments, only: [:create, :destroy]
  end


  get "messages/index"
  get "groups/index"
  resources :groups do
    resources :messages
  end

  resources :relationships,only: [:create, :destroy]
  resources :users,only: [:index, :edit, :update, :show] do
    member do
      get :following, :followers
    end
    
    resources :tweets do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end  
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true, unless: :image?
  belongs_to :user
  has_many :comments
  has_many :likes, dependent: :destroy
  mount_uploader :image, ImageUploader

  # 既にlike実行しているかのメソッド
  def like_user(user_id)
    likes.find_by(user_id: user_id)
   end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show]
  before_action :search_action,only: [:index, :new, :show, :edit,:world]
  before_action :all_ranks,only: [:index, :new, :show, :edit, :search,:world]

  def index
    @tweets = Tweet.includes(:user).order("created_at DESC").page(params[:page]).per(10)
    
    @user = current_user
    @users = @user.following
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(tweet_params)
    redirect_to action: :index 
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def edit
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
    redirect_to action: :index 
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index 
  end

  def search
    tweets = Tweet.includes(:user).order("created_at DESC").page(params[:page]).per(10)
    @q = tweets.search(search_params)
    @searches = @q.result(distinct: true)
  end

  def world
    @tweets = Tweet.includes(:user).order("created_at DESC").page(params[:page]).per(10)
  end

  private
  def tweet_params
    params.require(:tweet).permit(:image, :text).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id]) 
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  # -- サーチ機能--
  def search_action
    @q = Tweet.ransack(params[:q])
    @searches = @q.result(distinct: true)
  end

  def search_params
    params.require(:q).permit!
  end

  # -- ランキング機能--
  def all_ranks
    @all_ranks = Tweet.find(Like.group(:tweet_id).order('count(tweet_id) desc').limit(3).pluck(:tweet_id))
  end

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/modules/_header.html.haml
.tweet-header
  .tweet-header__serch
    = search_form_for @q, url: tweets_search_path do |f|
      .form_box
        = f.text_field :text_cont, class:'search-input',placeholder: "キーワードから探す"
        = f.submit "検索", class:'search-btn'
  .tweet-header__post.grid-1
    = link_to new_tweet_path, class: "post" do
      = icon('fas', 'pen-square', class: 'icon')
      %span 投稿

  .tweet-header__sign
    -if user_signed_in?
      .user_nav.grid-2
        = link_to "マイページ", user_path(current_user),class:"grid-1"
        -# = link_to "マイページ", user_path(current_user.id),class:"grid-1"
        = link_to "ログアウト", destroy_user_session_path, method: :delete,class:"grid-1"
      
    -else
      .grid-2
        = link_to "ログイン", new_user_session_path, class: 'post'
        = link_to "新規登録", new_user_registration_path, class: 'post' 
  
  

app/views/tweets/modules/_side_bar.html.haml
#sidebar.nav-collapse.tweet-sidebar
  / sidebar menu start
  = link_to root_path do
    %p.management-title Connect
 
    .my-image
      -if current_user.icon_image.url.nil?
      -else
        = image_tag(current_user.icon_image.url)
    .my-name
      = current_user.nickname
    %br
    
  %ul#nav-accordion.sidebar-menu
    = link_to root_path,class:"mm-title" do
      = icon('fas', 'bars', class: 'icon')
      Home / メニュー
  

    %li.mt
      = link_to root_path do
        = icon('fas', 'pen-square', class: 'icon')
        %span Home / ツイートリスト
      
    %li.sub-menu
      = link_to groups_path do
        = icon('far', 'comment', class: 'icon')
        %span Chat / チャット

    %li.sub-menu
      = link_to tweets_world_path do
        = icon('fas', 'globe-asia', class: 'icon')
        %span World / 全ツイート

    %hr 
  
  %ul#nav-accordion.sidebar-menu
    = link_to  user_path(current_user.id),class:"mm-title" do
      = icon('fas', 'user', class: 'icon')
      My page / メニュー

    %li.sub-menu
      = link_to  user_path(current_user.id) do
        = icon('fas', 'pen-square', class: 'icon')
        %span Profile / マイツイート

    -# %li.sub-menu
    -#   =link_to following_user_path(@user) do
    -#     = icon('fas', 'users', class: 'icon')
    -#     %span Follow /フォローリスト
      

  -#  %li
  -#     %a.active{:href => "inbox.html"}
  -#       %i.fa.fa-envelope
  -#       %span Mail
  -#       %span.label.label-theme.pull-right.mail-info 3

app/views/tweets/modules/_sidebar.html.haml
#sidebar.nav-collapse
  / sidebar menu start
  = link_to root_path do
    %p.management-title Connect

  -if user_signed_in?
    .my-image
      =link_to image_tag("gest.fujita.jpeg",class:"top-logo"),root_path
    .my-name
      = current_user.nickname
  - else
    .my-image
    .my-name
      No name
    
  %ul#nav-accordion.sidebar-menu
    = link_to root_path ,class:"mm-title" do
      -# = icon('fas', 'pen-square', class: 'icon')
      MENU
  

    %li.mt
      = link_to  user_path(current_user.id) do
        = icon('fas', 'pen-square', class: 'icon')
        %span MY PAGE

    %li.sub-menu
      = link_to new_tweet_path do
        = icon('fas', 'pen-square', class: 'icon')
        %span TWEET
      
    %li.sub-menu
      = link_to groups_path do
        = icon('fas', 'pen-square', class: 'icon')
        %span CHAT
    
    -# %li.sub-menu
    -#   = link_to root_path do
    -#     = icon('fas', 'pen-square', class: 'icon')
    -#     %span アイテム登録
      
    -# %li.sub-menu
    -#   = link_to root_path do
    -#     = icon('fas', 'pen-square', class: 'icon')
    -#     %span 予約管理
      
    -# %li
    -#   %a.active{:href => "inbox.html"}
    -#     %i.fa.fa-envelope
    -#     %span Mail
    -#     %span.label.label-theme.pull-right.mail-info 3
  

app/views/tweets/modules/_sub_bar.html.haml
.subbar
  .subbar__nav
    .left-block
    .right-block
    .follow
      .follow__lists
   




  .ranking
    %p ランキング(いいね数多いツイート)
    - @all_ranks.each.with_index(1) do |tweet, i| 
      .ranking__num
        第
        = i
        位
        .ranking__num__user
          =link_to user_path(tweet.id) ,class:"ranking-contentsr" do
            -if tweet.user.icon_image.present?
              = image_tag tweet.user.icon_image.url
            - else
              .ranking-image
              
            = tweet.user.nickname
        = link_to tweet_path(tweet.id) do
          = tweet.text
        %br
    
    